spring:
  datasource:
    url: jdbc:mysql://mysql-core-db-service:3306/banking_core_user_service
    username: javatodev_development
    password: oPItyPticIAt
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://internet-banking-service-registry:8081/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://openzipkin-server-service:9411/api/v2/spans

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://keycloak-web-service:8080
      realm: dungtm-internet-banking
      clientId: dungtm-internet-banking-kc-api-client
      client-secret: YS3UQXzAvEsUTfPM0qRpp7T1KAoTF8Y3
  feign:
    client:
      core-banking: internet-banking-core-banking-service
